config/routes.rb
Islandretreat::Application.routes.draw do
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/accommodation', :to => 'pages#accommodation'
  match '/location', :to => 'pages#location'
  match '/faq', :to => 'pages#faq'
  match '/visitors_book', :to => 'pages#visitors_book'
  match '/local_information', :to => 'pages#local_information'
  match '/rates', :to => 'pages#rates'
  match '/privacy', :to => 'pages#privacy'
  match '/terms', :to => 'pages#terms'
  match '/availability', :to => 'pages#availability'

  root :to => 'pages#home'

end

app/models/visitor.rb
# == Schema Information
# Schema version: 20110131094653
#
# Table name: visitors
#
#  id         :integer         not null, primary key
#  date       :string(255)
#  comment    :text
#  created_at :datetime
#  updated_at :datetime
#

class Visitor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    @header = "Island Retreat"
    @comment = "Having visited the Island on and off for 40 years, this is the best accommodation we have stayed in. Will be back. Keith, Lou and Victoria"
  end

  def contact
    @title = "Contact"
    @header = "Contact Us"
    @comment = "Really impressed with Island Retreat, location, parking, everything was first class. Dawn"
  end

  def about
    @title = "About"
    @header = "About Us"
    @comment = "Thank you very much for accommodating us on our short break. Your bungalow was lovely with everything we needed. Would recommend to friends & family. 'The Priddles'"
  end

  def accommodation
    @title = "Accommodation"
    @header = "Accommodation"
    @comment = "Accommodation very comfortable, first stay at Island Retreat, everything thought of and superbly clean. Thank you! Coral Lynn, Fred & Alex"
  end

  def faq
    @title = "FAQ"
    @header = "Frequently Asked Questions"
    @comment = "Once again an excellent place to stay, we have thoroughly enjoyed our two weeks here on the IOW and in the bungalow. Accommodation very good, beds were lovely and comfortable and garden was lovely to sit in and Jodie the dog to have a run around in. David, Sue, Janet and John"
  end

  def visitors_book
    @title = "Visitor's Book"
    @header = "Visitor's Book"
    @visitors = Visitor.find(:all, :order => "id DESC")
    @comment = "This is the best self-catering accommodation we have stayed in. Truly home from home. Fabulous week even though the weather wasn't always kind to us. We and the dogs have just loved it here. Thank you so much. We will be back! Hancock Party"
  end

  def local_information
    @title = "Local Information"
    @header = "Local Information"
    @comment = "Really peaceful surroundings. Great Bungalow. Will certainly come again. Purchell Party"
  end

  def rates
    @title = "Rates"
    @header = "Rates"
    @comment = "Back for our 2nd year and we hope to see you again. This really is a home from home, we felt comfortable the minute we came through the door! Had a lovely week. Thank you so much. Jackson Party"
  end

  def privacy
    @title = "Privacy"
    @header = "Privacy Policy Statement"
    @comment = "We always do a cottage or a bungalow, self catering and this is the best yet. Very clean and well equipped. Had a great week, our 1st visit to IOW. Will definitely come again and this will be our 1st choice of accommodation. Dave , Max, Sue and Katie"
  end

  def terms
    @title = "Terms"
    @header = "Terms of Service"
    @comment = "Everything was absolutely ideal for us. 1st visit to both the island and the bungalow - definitely won't be our last! Hatfield Party"
  end

  def availability
    @title = "Availability"
    @header = "Availability"
    @comment = "Absolutely wonderful - we have had such a lovely week. Weather has been perfect & the bungalow is very comfortable & a great location. Our 5th visit to Island Retreat. Thanks. Howell Party"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Island Retreat Holiday Cottage"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  # Return logo
  def logo
    image_tag("logo_ir.jpg", :alt => "Island Retreat")
  end

  # Picture Front
  def front_image
    image_tag("front.jpg", :alt => "Front View of Island Retreat")
  end

  def front_text
    "Front View of Island Retreat"
  end

  # Picture rear garden
  def rear_garden_image
    image_tag("garden.jpg", :alt => "Garden of Island Retreat")
  end

  def rear_garden_text
    "Rear Garden ( Fully Enclosed )"
  end

  # picture lounge
  def lounge_image
    image_tag("lounge.jpg", :alt => "Lounge of Island Retreat")
  end

  def lounge_text
    "Lounge/Diner"
  end

  # picture kitchen
  def kitchen_image
    image_tag("kitchen.jpg", :alt => "Kitchen of Island Retreat")
  end

  def kitchen_text
    "Kitchen/Diner"
  end

  # picture double
  def double_image
    image_tag("double.jpg", :alt => "Double Bedroom of Island Retreat")
  end

  def double_text
    "Double bedroom"
  end
 
  # picture twin
  def twin_image
    image_tag("twin.jpg", :alt => "Twin Bedroom of Island Retreat")
  end

  def twin_text
    "Twin bedroom"
  end 

 
  # picture needles
  def needles_image
    image_tag("needles.jpg", :alt => "The Needles")
  end

  def needles_text
    "The Needles"
  end 

  # picture godshill
  def godshill_image
    image_tag("godshill.jpg", :alt => "Godshill Village")
  end

  def godshill_text
    "Godshill Village"
  end 

  # picture freshwater
  def freshwater_image
    image_tag("freshwater_bay.jpg", :alt => "Freshwater Bay")
  end

  def freshwater_text
    "Freshwater Bay"
  end 

  # picture ryde
  def ryde_image
    image_tag("ryde_seafront.jpg", :alt => "Ryde Beach")
  end

  def ryde_text
    "Ryde Beach"
  end 

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_accommodation.html.erb
<div>

	<div>
		<h3>Island Retreat</h3> 

		<strong>A detached bungalow:</strong>
		<ul>
			<li>Peaceful surroundings</li>
			<li>Private and enclosed rear garden with patio and garden furniture</li>
			<li>Safe off-road parking at the rear of the property</li>
		</ul>
	</div>
	
	<img src="/photos/P1010838.JPG" />

</div>



<div>

	<div>

		<h3>The Rear Garden</h3> 

		<strong>Fully enclosed spacious rear garden</strong> 

		<ul>
			<li>Sun patio</li>
			<li>Picnic table and chairs</li>
			<li>Safe off-road parking behind the garden</li>
		</ul>

	</div>
	
	<img src="/photos/P1010840.JPG" />
	
</div>

<div>

	<div>
		<h3>The Lounge/Diner</h3> 

		<strong> 
		Comfortable carpeted lounge overlooking the rear garden
		</strong> 

		<ul>
			<li>Two comfy sofas</li>
			<li>28" wide screen TV</li>
			<li>DVD/VCR machine</li>
			<li>Freeview receiver for digital TV</li>
			<li>Hi-fi</li>
			<li>Dining table and chairs</li>
		</ul>
	</div>
	
	<img src="/photos/P1010829.JPG" />
	
</div>

<div>
	
	<div>

		<h3>Kitchen/Diner</h3> 

		<strong>Fully fitted modern kitchen/diner	</strong> 

		<ul>
			<li>Double oven </li>
			<li>Fridge/Freezer</li>
			<li>Microwave</li>
			<li>Dishwasher</li>
			<li>Washing machine</li>
			<li>Dining table &amp; chairs </li>
		</ul>
	</div>
	<img src="/photos/P1010859.JPG" />
</div>

<div>
	<div>

		<h3>Double Bedroom</h3> 

		<strong> 
		Bedroom with double bed
		</strong> 

		<ul>
			<li>Double Bed</li>
			<li>Wardrobe and chest of drawers </li>
			<li>Bedside tables</li>
			<li>Reading lights</li>
		</ul>
	</div>
	
	<img src="/photos/P1010827.JPG" />
	
</div>

<div>

	<div>

		<h3>Twin bedroom</h3> 

		<strong> 
		Bedroom with twin beds
		</strong> 

		<ul>
			<li>2 single beds (mattresses replaced in 2011)</li>
			<li>Wardrobe and chest of drawers</li>
			<li>Bedside table</li>
			<li>Reading light</li>
		</ul>				
	</div>
	<img src="/photos/P1010822.JPG" />
</div>

<div>

	<div>

		<h3>At the back of the property</h3>

		<strong>
		Park with playground
		</strong>

		<ul>
			<li>Perfect for pet walking </li>
			<li>Children's park</li>
			<li>No roads to cross to get there</li>
		</ul>
	</div>
	<img src="/photos/P1010847.JPG" />
</div>

app/views/layouts/_contact.html.erb
<h1>Contact Us</h1>

<p>For further information or for availability queries please email Meghan at 
    <script language="JavaScript">
    document.write('<a h'+'ref="m'+'ailt'+'o:'+'%69%6e%66%6f%40%69%73%6c%61%6e%64%72%65%74%72%65%61%74%2e%63%6f%2e%75%6b">&#105;&#110;&#102;&#111;&#64;&#105;&#115;&#108;&#97;&#110;&#100;&#114;&#101;&#116;&#114;&#101;&#97;&#116;&#46;&#99;&#111;&#46;&#117;&#107;<\/a>');
    </script>
</p>
<p>or call 01444 239645</p>

<p> I will try to answer your query as soon as possible but if you need to know availability immediately join my mailing list below and it will be emailed to you automatically.</p>

<p>

app/views/layouts/_faq.html.erb
<script type="text/javascript">
$(document).ready(function() {
        $(".showcode").click (function() {
                $(this).next().toggle(300);
        return false;
        });
});
</script>


<p class="showcode"><a href="#" >How do I get to the Isle of Wight?</a></p>
<div style="display:none;">
<p>Your route is likely to depend on where you live. The Isle of Wight can be reached by either a car ferry or a passenger ferry from Portsmouth or Lymington via <a href="http://www.wightlink.co.uk" target="_blank">Wightlink Ferries</a> or Southampton via <a href="http://www.redfunnel.co.uk" target="_blank">Red funnel Ferries</a>.<p>
</div>


<p class="showcode"><a href="#" >How far from the ferry port?</a></p>
<div style="display:none;">
<p>Island Retreat is a 5 minute drive away from both Fishbourne car ferry port and Ryde passenger ferry port.</p>
<p>Yarmouth ferry port is about 30 minutes away for those taking the Lymington to Yarmouth ferry route</p>
</div>

<p class="showcode"><a href="#" >What linen is provided?</a></p>
<p style="display:none;">Linen is not provided.</p>

<p class="showcode"><%= link_to "What bedding is provided?", "#" %></p>
<p style="display:none;">One duvet plus two pillows per person. We also supply a dog bed. </p>

<p class="showcode"><%= link_to "What is included in the price?", "#" %></p>
<p  style="display:none;">Gas and electric. Change-over clean.</p>

<p class="showcode"><%= link_to "How many pets can I bring?", "#" %></p>	
<p  style="display:none;">You can bring a maximum of two pets.</p>
  
<p class="showcode"><%= link_to "How much do you charge for pets?", "#" %></p>
<p  style="display:none;">We charge £10.00 per pet. Up to two pets are welcome.</p>

<p class="showcode"><%= link_to "Where is the parking?", "#" %> </p>
<div style="display:none;">
	<p>The bungalow is set a fair way back from the road. There is actually a green in front and a pavement between the green and the bungalow's front garden. </p>
	<p>At the back of the bungalow there is a parking area and garages servicing about six bungalows. You can access the parking area via another road and park your car adjacent to the back of the garden fence, you then access the bungalow through the back gate, and up the garden path. </p>
	<p>We hardly ever use the front door unless we're going out on foot. </p>
	<p>As you can see, this arrangement makes it very safe for children because there is no road for them to easily run into and it is also very quiet. It is also very safe for your car because no one can see it from the road, not that it is an unsafe area by any means. </p>
</div>
	
<p class="showcode"><%= link_to "What is the address?", "#" %></p>
<p style="display:none;">We send out the address plus full directions when we receive full payment. We ask for full payment eight weeks before your holiday.</p>

<p class="showcode"><%= link_to "Is there a telephone?", "#" %> </p>
<p style="display:none;">There is a telephone for 999 calls only.  </p>


<p class="showcode"><%= link_to "What if I have any problems with the bungalow during my stay?", "#" %> </p>
<p style="display:none;">The information pack in the bungalow will provide all the information you need, including telephone numbers to call should there be a problem during your stay.</p>

<p class="showcode"><%= link_to "How will I get the keys?", "#" %> </p>
<p style="display:none;">You will receive details of how to get the keys eight weeks before your stay (when the balance is paid).</p>

<p class="showcode"><%= link_to "What are the check-in and check-out times?", "#" %> </p>
<p style="display:none;">The bungalow will be available from 4pm on your arrival day and you need to vacate by 10am </p>

<p class="showcode"><%= link_to "Can I Smoke?", "#" %></p>
<p style="display:none;">Sorry, no.</p>


<p class="showcode"><%= link_to "Do I have to clean the property before I leave?", "#" %></p>
<p style="display:none;">Please leave the bungalow in a clean and tidy state. The bungalow will be thoroughly cleaned by our caretaker after you leave.</p>

<p class="showcode"><%= link_to "My holiday is for two weeks can I have a mid-holiday clean? ", "#" %></p>
<p style="display:none;">Yes you can, this is provided at no extra charge.</p>

<p class="showcode"><%= link_to "When is the change-over day?", "#" %></p>
<div style="display:none;">
<p>For weekly stays it is Saturday to Saturday. </p>
<p>Three night short breaks can start on a Friday or Saturday </p>
<p>Four night short breaks can start on a Saturday , or Monday. If you require a different start-day (for a short-break only) during off-peak periods please <%= link_to "contact me", contact_path %>. </p>
</div>

<p class="showcode"><%= link_to "Does the local pub allow dogs?", "#" %></p>
<p style="display:none;">The nearest pub is the Fleming Arms in Binstead Road. It allows dogs, but only in certain areas.</p>

<p class="showcode"><%= link_to "What garden furniture is supplied?", "#" %></p>
<p style="display:none;">Four chairs and a table, umbrella, barbeque and utensils plus some deck chairs. There may be some barbeque charcoal. We leave a bag at the beginning of the season, when its gone its gone! </p>

<p class="showcode"><%= link_to "How far from the beach?", "#" %></p>
<p style="display:none;">Ryde beach is a 5 minute drive or a 20 minute walk. </p>

<p class="showcode"><%= link_to "What are the payment terms?", "#" %></p>
<div style="display:none;">
      <p>A deposit of 20% to secure the booking. Full payment must be received at least eight weeks before your arrival date. For a last-minute booking full payment must be made at the time of booking. </p>
      <p>All monies received are non-refundable. </p>
</div>

<p class="showcode"><%= link_to "When do I pay the balance?", "#" %></p>
<p style="display:none;">Eight weeks before your arrival date.</p>

<p class="showcode"><%= link_to "Is the bungalow heated?", "#" %></p>
<p style="display:none;">Yes it has a combination boiler, giving you immediate hot water. </p>

<p class="showcode"><%= link_to "Is the bungalow double-glazed?", "#" %> </p>
<p style="display:none;">Yes</p>

<p class="showcode"><%= link_to "Is there a tumble dryer?", "#" %> </p>
<p style="display:none;">No, but we supply a washing line and an airer for drying indoors. </p>

app/views/layouts/_footer.html.erb
<p>
  <%= link_to "Privacy Notice", privacy_path %> , <%= link_to "Terms of Service", terms_path %>
</p>
<p>
  <%= link_to root_url, root_path %>
</p>

app/views/layouts/_gallery.html.erb
<%= stylesheet_link_tag 'scrollable-horizontal.css', :media => 'screen' %>
<%= stylesheet_link_tag 'scrollable-buttons.css', :media => 'screen' %>
<%= stylesheet_link_tag 'scrollable-navigator.css', :media => 'screen' %>


<!-- wrapper for navigator elements --> 
<div class="navi"></div> 
 
 
 
<!-- "previous page" action --> 
<a class="prev browse left"></a> 
 
<!-- root element for scrollable --> 
<div class="scrollable" id=chained>   
   
   <!-- root element for the items --> 
   <div class="items"> 
   
      <!-- 1-3 --> 
      <div> 
         <img src="/photos/P1010838.JPG" />
	 <img src="/photos/P1010840.JPG" />
         <img src="/photos/P1010860.JPG" />
         <img src="/photos/P1010829.JPG" />
         
      </div> 
      
      <!-- 4-6 --> 
      <div> 
	 <img src="/photos/P1010858.JPG" />
         <img src="/photos/P1010859.JPG" />
         <img src="/photos/P1010822.JPG" />
         <img src="/photos/P1010827.JPG" />
      </div> 


      <!-- 4-6 -->
      <div>
   	 <img src="/photos/P1010832.JPG" />
         <img src="/photos/P1010834.JPG" />
         <img src="/photos/P1010847.JPG" />
         <img src="/photos/P1010848.JPG" />

      </div>



      
   </div> 
   
</div> 
 
<!-- "next page" action --> 
<a class="next browse right"></a> 
 
 
<br clear="all" /> 
 
<!-- javascript coding --> 
<script> 
// What is $(document).ready ? See: http://flowplayer.org/tools/documentation/basics.html#document_ready
$(document).ready(function() {
 
// heeeeeeeeeeere we go.
$("#chained").scrollable({mousewheel: true}).navigator();	
});
</script> 
 

app/views/layouts/_header.html.erb
<div id="headercol1"><%= link_to logo, root_path %></div>
<div id="headercol2">
<p><%= @comment %> 
<%=link_to "more ...", visitors_book_path%>
</p>
</div>

app/views/layouts/_latestavailability.html.erb
<h1><%= link_to "Latest Availability", availability_path %></h1>
<p>This is the latest availability for 2011 at Island Retreat. <%= link_to "Book Up Now", availability_path %></p>
<p>Island Retreat is fully booked for the summer until October. See below for autumn and winter holiday dates. If you would like to book a short break check the <%= link_to "availability page", availability_path %> for more information.</p>

<div id="availability">

<table><th>Start Date</th><th>End Date</th><th>Price</th></tr><tr onMouseOver="this.className='highlight';" onMouseOut="this.className='';" ><td>Saturday 8th October 2011</td><td>Saturday 15th October 2011</td><td>£280.00</td></tr><tr onMouseOver="this.className='highlight';" onMouseOut="this.className='';" ><td>Saturday 15th October 2011</td><td>Saturday 22nd October 2011</td><td>£280.00</td></tr><tr onMouseOver="this.className='highlight';" onMouseOut="this.className='';" ><td>Saturday 12th November 2011</td><td>Saturday 19th November 2011</td><td>£200.00</td></tr><tr onMouseOver="this.className='highlight';" onMouseOut="this.className='';" ><td>Saturday 19th November 2011</td><td>Saturday 26th November 2011</td><td>£200.00</td></tr><tr onMouseOver="this.className='highlight';" onMouseOut="this.className='';" ><td>Saturday 26th November 2011</td><td>Saturday 3rd December 2011</td><td>£200.00</td></tr><tr onMouseOver="this.className='highlight';" onMouseOut="this.className='';" ><td>Saturday 3rd December 2011</td><td>Saturday 10th December 2011</td><td>£200.00</td></tr><tr onMouseOver="this.className='highlight';" onMouseOut="this.className='';" ><td>Saturday 10th December 2011</td><td>Saturday 17th December 2011</td><td>£200.00</td></tr></table>

</div>

app/views/layouts/_local_information.html.erb
	<h1>Local Information</h1>
	<p>
	The <%= link_to "Isle of Wight Council web site", "http://www.iwight.com/just_visiting/default.asp", :target => "_blank" %> provides useful information for visitors.
	</p>

	<p>Discover the Isle of Wight through the Tourists boards' official website</p>
	<p><%= link_to "www.islandbreaks.co.uk", "http://www.islandbreaks.co.uk", :target => "_blank" %></p>
	<p><%= link_to "Isle of Wight Walking Festival", "http://www.isleofwightwalkingfestival.co.uk", :target => "_blank" %>
	</p>
	<p>
	<%= link_to "Local Businesses and Suppliers in Isle Of Wight", "http://www.suppliersnearby.co.uk/area/Isle_of_wight.html", :target => "_blank" %>
	</p>
	<p> 
	<%= link_to image_tag("sunny_day.gif", :alt => "Island Retreat"), "http://www.bbc.co.uk/weather/5day.shtml?world=4207&links=b" %>

	View the <%= link_to "5 day Isle of Wight weather forecast", "http://www.bbc.co.uk/weather/5day.shtml?world=4207&links=b", :target => "_blank" %>
	</p>
	<p>For travelling to the Isle of Wight with your car or as a foot passenger Island Retreat recommends <%= link_to "Wightlink Ferries", "http://www.wightlink.co.uk", :target => "_blank" %>. Island Retreat is only a five minute drive from Fishbourne car ferry terminal.</p>

app/views/layouts/_maininfo.html.erb
<h1><%= @header %></h1>




<p>
'Island Retreat' is a family owned and run holiday bunglalow located in Binstead near Ryde on the Isle of Wight. It is available for holiday rentals all year round and short breaks during off-peak periods.
</p>

<p>
'Island Retreat' is a single story detached bungalow which comfortably caters for four people. It has <strong>one double bedroom and one twin</strong> and has been described by many of its past <%= link_to "guests", visitors_book_path %> as a 'home from home'.
</p>

<p>
Binstead is a quiet village in the northern part of the island and is a five minute drive away from Fishbourne car ferry terminal.</p>

<p>
The bungalow is ideal accommodation for all ages. The spacious garden is accessed by french doors from the kitchen and is fully enclosed. There is a large park with a children's playground at the back of the property, perfect for exercising pets (or children!). The bungalow is set a long way back from a very quiet residential road.
</p>

		<ul>
			<li>comfortably caters for 4 people</li>
			<li>located in a quiet residential area</li>
			<li>set back from the road and backs onto a park with a children's play area </li>
			<li>recently replaced kitchen/diner with french doors opening onto the garden 			
			<li> spacious enclosed garden with patio and garden furniture</li>
			<li> recently replaced bathroom including a bath with power shower over </li>
			<li> all mod-cons including wide screen TV and DVD player  
			<li>five minute drive from  Ryde beach and Fishbourne car ferry terminal</li>
			<li>local shop, pub and post office within walking distance of the property </li>
			<li>convenient off-road parking</li>
			<li>centrally heated </li>
			<li>pets are welcome (dog bed is supplied) </li>
			<li>no smoking allowed within the property </li>
		</ul>


<div id="scrollingpics" class="grbox noborder">
    <%= render 'layouts/gallery' %>
</div>

		<div id="mainlink">
			<ul>
		  	<li><%= link_to "View the accommodation", accommodation_path %></li>
	      <li><%= link_to "Find out about the local area", local_information_path %></li>
	      <li><%= link_to "Check availability and book your accommodation online", availability_path %></li>
		  </ul>
		</div>
        
		<p>Have a question? Check the <%= link_to "frequently asked questions", faq_path %> page or  <%= link_to "contact us", contact_path %></p>

app/views/layouts/_menu.html.erb
<ul>
  <li><%= link_to "Accommodation", accommodation_path %></li>
  <li><%= link_to "Location", location_path %></li>
  <li><%= link_to "FAQ", faq_path %></li>
  <li><%= link_to "Local Information", local_information_path %></li>
  <li><%= link_to "Visitor's Book", visitors_book_path %></li>
  <li><%= link_to "Rates", rates_path %></li>
  <li><%= link_to "Availability & Booking", availability_path %></li>
  <li><%= link_to "Contact Us", contact_path %></li>
</ul>

app/views/pages/home.html.erb
<div class="grbox noborder">
    <p class="quote">"Excellent bungalow, everything has been thought of, even the weather has been excellent, our third visit and we have enjoyed it as much as   the first time." Roberts Party <%= link_to "read more ...", visitors_book_path %></p>
</div>

<div class="grbox smallcol left noborder">
  <%= render 'layouts/pets' %>
</div>



<div class="grbox largecol right">
	<%= render 'layouts/maininfo' %>		
</div>

<div class="grbox smallcol left">
  <h1>Island Retreat</h1>
  <p><img src="/photos/P1010838.JPG" /></p>
</div>


 <div class="grbox smallcol left">
     <%= render 'layouts/latestavailability' %>     
 </div>

 <div class="grbox smallcol left">
     <%= render 'layouts/mailinglist' %>
 </div>

app/views/pages/rates.html.erb
<div class="grbox right largecol">
<h1>Rates</h1>
<p>
The change over day is Saturday for weekly bookings. Short breaks are available in low season and may start on Friday, Saturday, Sunday or Monday.
</p>

<p>
Up to two pets are welcome, and the charge is £10.00 per pet.
</p>

<p>
Bookings are held for 7 days until a 20% deposit is received. Full payment must be made 8 weeks before the booking date. The deposit is unrefundable.
</p>

<p>
The breakages deposit is £100 per week which will be refunded when the property has been checked and found to be in a satisfactory state.
</p>

<p>Island Retreat is open all year.</p>

<p><%= link_to "Check Availability", availability_path %></p>


<iframe src="http://cottagemaster.co.uk/rates.php?mid=1" width="100%" frameborder="0" title="Rates for 2011" height="300px"></iframe>
</div>

<div class="grbox smallcol noborder">
	<%= render 'layouts/pets' %>
</div>

<div id = "latestavailability2" class="grbox smallcol">
  <%= render 'layouts/latestavailability' %>     
</div>

app/views/pages/terms.html.erb
<div class="grbox">
<h1>Terms of Service</h1>
<p><strong>Our contract </strong></p>
		<p>When you place a booking with islandretreat.co.uk you will receive an email confirming availability and price. A booking made through the website will be held for a maximum of seven days until either a deposit or full payment is received. Full payment must be received at least six weeks before the arrival date after which time islandretreat reserves the right to re-advertise the holiday and all monies paid by the customer will be forfeited.</p>
		<p>Islandretreat endeavors to provide you with accommodation as described within the website and in full working order. In the unlikely event that this is not possible due to breakages or breakdowns that have occured during a previous rental period, we will make an assessment as to whether we can provide you with accommodation that meets your expectations, if not then a full refund will be applied. </p>
		<p><strong>Cancellations</strong></p>
		<p>Once a booking has been placed any payment made to islandretreat to secure the booking is non-refundable. In the event that islandretreat cancels a booking a full refund will be applied. </p>
		<p><strong>Pricing and Availability </strong></p>
		<p>We list availability on the website. This is as accurate as we can possibly make it but we reserve the right to refuse a booking on the grounds of unavailability despite the website stating the contrary. We may advertise holidays elsewhere at a different price to that advertised on the website. Once we have accepted a booking the price is fixed. </p>
		<p><strong>Privacy </strong></p>
		<p>Please review our <%= link_to "Privacy Notice", privacy_path %> , which also governs your visit to islandretreat.co.uk, to understand our practices. </p>
		<p><strong>Licence for website access </strong></p>
		<p>Islandretreat,co.uk grants you a limited licence to access and make personal use of this website, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of islandretreat.co.uk. This licence does not include any resale or commercial use of this website or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this website or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. </p>
		<p>This website or any portion of this website may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without our express written consent. </p>
		<p>You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of islandretreat.co.uk without express written consent. You may not use any meta tags or any other "hidden text" utilising islandretreat.co.uk's without the express written consent of islandretreat.co.uk. Any unauthorised use terminates the permission or license granted by islandretreat.co.uk. </p>
		<p><strong>Your conduct </strong></p>
		<p>You must not use the website in any way that causes, or is likely to cause, the website or access to it to be interrupted, damaged or impaired in any way. </p>
		<p>You understand that you, and not islandretreat.co.uk, are responsible for all electronic communications and content sent from your computer to us and you must use the website for lawful purposes only. </p>
</div>